### ISSUE TITLE
Installation issue with gcc

### ISSUE THREAD

**Issue by MikiSchikora** [histed/lowess-work-carljv#1]
Good afternoon,

I am trying to install this repository as a python package in a conda environment (called perSVade_env, which is defined in https://github.com/Gabaldonlab/perSVade/blob/master/installation/perSVade_env.yml) inside a docker image. This is how the Dockerfile looks like:

"""
FROM continuumio/miniconda3:4.8.2

WORKDIR /perSVade_env

COPY . .

RUN conda install -y -c conda-forge mamba=0.15.3

RUN mamba env create --file perSVade_env.yml --name perSVade_env

RUN conda install -y -n perSVade_env -c conda-forge gcc=11.1.0

SHELL ["conda", "run", "-n", "perSVade_env", "/bin/bash", "-e", "-c"]

RUN git clone https://github.com/histed/lowess-work-carljv
RUN python lowess-work-carljv/setup.py install

"""

When I try to build the image, I get the following error:

"""
running install
running build
running build_ext
skipping 'cylowess.c' Cython extension (up-to-date)
building 'cylowess' extension
creating build
creating build/temp.linux-x86_64-3.6
gcc -pthread -B /opt/conda/envs/perSVade_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include -I/opt/conda/envs/perSVade_env/include/python3.6m -c cylowess.c -o build/temp.linux-x86_64-3.6/cylowess.o
creating build/lib.linux-x86_64-3.6
gcc -pthread -shared -B /opt/conda/envs/perSVade_env/compiler_compat -L/opt/conda/envs/perSVade_env/lib -Wl,-rpath=/opt/conda/envs/perSVade_env/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cylowess.o -o build/lib.linux-x86_64-3.6/cylowess.cpython-36m-x86_64-linux-gnu.so

Cloning into 'lowess-work-carljv'...
In file included from /opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cylowess.c:275:
/opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
cylowess.c:5374:13: warning: '__pyx_pw_5numpy_7ndarray_3__releasebuffer__' defined but not used [-Wunused-function]
 5374 | static void __pyx_pw_5numpy_7ndarray_3__releasebuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cylowess.c:4558:12: warning: '__pyx_pw_5numpy_7ndarray_1__getbuffer__' defined but not used [-Wunused-function]
 4558 | static int __pyx_pw_5numpy_7ndarray_1__getbuffer__(PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:21,
                 from /opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cylowess.c:275:
/opt/conda/envs/perSVade_env/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: '_import_array' defined but not used [-Wunused-function]
 1463 | _import_array(void)
      | ^~~~~~~~~~~~~
cylowess.c: In function '__pyx_pw_8cylowess_5update_indices':
cylowess.c:3938:13: warning: '__pyx_v_k' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3938 |   __pyx_t_3 = (__pyx_v_k - 1);
      |   ~~~~~~~~~~^~~~~~~~~~~~~~~~~
cylowess.c:3796:14: note: '__pyx_v_k' was declared here
 3796 |   Py_ssize_t __pyx_v_k;
      |              ^~~~~~~~~
/opt/conda/envs/perSVade_env/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/opt/conda/envs/perSVade_env/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

"""

Do you know whether this can be solved? 

Thanks for your time.

**Comment by histed** [comment]
I'm sorry, I have not worked on this code in some time. I'll be archiving the repository now. I would investigate what scipy and scikit-learn currently provide.  Cheers!
